<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Скидка 10% на все товары!");
?>  
<h3 style="margin: 0px 0px 10px; padding: 0px; outline: 0px; font-style: normal; font-variant: normal; font-weight: normal; font-size: 18px; line-height: normal; font-family: Arial, Helvetica, sans-serif; color: rgb(66, 66, 66); letter-spacing: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Скидка 10% на все товары!</h3>

<div style="margin: 0px; padding: 0px; outline: 0px; color: rgb(66, 66, 66); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Дисконтная карта &laquo;Бэстпрайс&raquo; - это уникальная возможность<span class="Apple-converted-space"> </span><font color="#ff0000" style="margin: 0px; padding: 0px; outline: 0px;">получить скидку 10%</font><span class="Apple-converted-space"> </span>на все приобретаемые товары в магазинах «Бэстпрайс».</div>

<br style="margin: 0px; padding: 0px; outline: 0px; color: rgb(66, 66, 66); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" />
<span style="color: rgb(66, 66, 66); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">Получить дисконтную карту очень просто! Совершите покупку на сумму от 200 000, заполните анкету и дисконтная карта Ваша.<span class="Apple-converted-space"> </span></span>
<br style="margin: 0px; padding: 0px; outline: 0px; color: rgb(66, 66, 66); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" />

<br style="margin: 0px; padding: 0px; outline: 0px; color: rgb(66, 66, 66); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" />
<span style="color: rgb(66, 66, 66); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">Картой могут пользоваться ваши друзья и знакомые, мы не против.<span class="Apple-converted-space"> </span></span>
<br style="margin: 0px; padding: 0px; outline: 0px; color: rgb(66, 66, 66); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" />

<br style="margin: 0px; padding: 0px; outline: 0px; color: rgb(66, 66, 66); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" />
<span style="color: rgb(66, 66, 66); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">- ЗАПОЛНЕНИЕ АНКЕТЫ ЯВЛЯЕТСЯ ОБЯЗАТЕЛЬНЫМ УСЛОВИЕМ ДЛЯ УЧАСТИЯ В ДИСКОНТНОЙ ПРОГРАММЕ! Компания вправе отказать в активации либо аннулировать действие уже активированной дисконтной карты в случае, если в анкете присутствуют незаполненные поля, поля, заполненные неразборчивым почерком либо информация, указанная в анкете, не соответствует действительности.<span class="Apple-converted-space"> </span></span>
<br style="margin: 0px; padding: 0px; outline: 0px; color: rgb(66, 66, 66); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" />
<span style="color: rgb(66, 66, 66); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">- Держатель дисконтной карты вправе передать ее другим лицам на свое усмотрение. Ответственность за последствия связанные с такой передачей дисконтной карты в полном объеме возложена на держателе этой дисконтной карты.<span class="Apple-converted-space"> </span></span>
<br style="margin: 0px; padding: 0px; outline: 0px; color: rgb(66, 66, 66); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" />
<span style="color: rgb(66, 66, 66); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">- Компания «Бэстпрайс» оставляет за собой право менять правила проведения дисконтной программы без специального предварительного уведомления ее участников. Также компания «Бэстпрайс» вправе в любой момент прекратить действие дисконтной программы. В обоих случаях информация об изменениях размещается на сайте компании.</span>  <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>